### ISSUE TITLE
api token is viewable

### ISSUE THREAD

**Issue by mohammad6006** [kasramp/geekswebbot#2]
api code is visible by everyone
Does it normal?

**Comment by kasramp** [comment]
@mohammad6006, I had a look at your changes in the fork repo. You are not suppose to commit API token to your code base. Better revert back your commit.
My recommended approach is to read API key either from database or a property file. Or if you want to use it as is do not commit the API token to Github, just add the key in production (not recommended).
If you decided to go with the first way, you should change this line
`$client = new Zelenin\Telegram\Bot\Api(''); // Set your access token`

**Comment by mohammad6006** [comment]
but I use heroku and dont have access to file manager

**Comment by kasramp** [comment]
Hi, I missed out your question. Anyway, I believe Heroku provides some persistence for each application, you can utilize that one, have a look at the documentation.
If you couldn't make it work, Heroku provides database instance as well, you can store your credential there.
If that one didn't work, there is another way I can think of which is to upload your credential to S3 bucket and read it in your app or something similar to that.
