### ISSUE TITLE
upgrade telegram-bot-api

### ISSUE THREAD

**Issue by mohammad6006** [kasramp/geekswebbot#4]
after upgrade zelenin/telegram-bot-api to version 1

`PHP Fatal error: Uncaught TypeError: Argument 1 passed to Zelenin\Telegram\Bot\Api::__construct() must be an instance of Zelenin\Telegram\Bot\Client\Client, string given, called in /app/index.php on line 24 and defined in /app/vendor/zelenin/telegram-bot-api/Api.php:26`

`public function __construct(Client $client)
    {
        $this->client = $client;
    }
`

**Comment by mohammad6006** [comment]
`$client = Zelenin\Telegram\Bot\ApiFactory::create($token);
`
solved

**Comment by kasramp** [comment]
Great :+1:

**Comment by IldeNet** [comment]
You can write the code here? I also have problems with version 1.5.0 of Zelenin

**Comment by mohammad6006** [comment]
@IldeNet  
after upgrade Zelenin you should use :
`$client = Zelenin\Telegram\Bot\ApiFactory::create($token);`
in index.php
instead of 
`$client = new Zelenin\Telegram\Bot\Api('AccessToken');`

**Comment by IldeNet** [comment]
@mohammad6006 
Thank you very much. I was going crazy. I owe you a beer!
now I can use the command leaveChat. but still I do not know how to stop in case of error. for example:
$response = $client-> leaveChat ([ 'chat_id' => '12345']);
